### ISSUE TITLE
MKR1000

### ISSUE THREAD

**Issue by harryhawkes** [WorldFamousElectronics/PulseSensorPlayground#110]
Hi, I am doing a project for university with this pulse sensor using the MKR1000 Wifi board. i understand that from using the BPM_Alternative script you have greatly provided this should work fine, however i am hoping to use a few other sensors i.e. pressure sensor and temperature sensor. From your example script, it says 'don't place any code here or it could slow sampling from sensor'. I was basically wondering could i not wrap this sketch up into a function and call when i need, and then jump out of function and carry on with the rest of my sketch for rest of the sensors etc? would this still affect the pulse sensor readings or should i be okay? i don't need a continuous reading from this, and would be happy with one every so often as principle is more important i think than actual perfect reading?

Thanks,

**Comment by biomurph** [comment]
@harryhawkes 
The BPM_Alternative code uses a software timer to sample the Pulse Sensor at 500Hz (every 2 milliseconds). Since this is happening in software, it is important not to introduce any delays or code that takes a long time to execute. For example, if you are doing any serial output of your other sensor data, keep the baud rate as fast as you can. Note that 9600 baud rate will take 1 millisecond to send 1 byte!

Take a look at the sketch in 
`File > Examples > Digital > BlinkWithoutDelay`
for a useful example to work from to design your own software timer to handle your sensor readings from the pressure and temperature sensors. As you mentioned, these sensors do not require reading very often, as they likely won't change very fast. Especially the temperature sensor.

When you have some code written up, please post a link to it here if you are having trouble.
