### ISSUE TITLE
It does not work on D1mini or esp8266,

### ISSUE THREAD

**Issue by YoYoHC** [WorldFamousElectronics/PulseSensorPlayground#128]
It can run on uno but it does not work on D1mini or Esp8266. Can you help me?

**Comment by biomurph** [comment]
I need more information to help you.
What sketch are you trying to run?
Please also attach a picture of your Pulse Sensor to verify the hardware.

**Comment by YoYoHC** [comment]
![serson](https://user-images.githubusercontent.com/54131204/87495705-a0901000-c684-11ea-8c33-51d23384c249.png)
This is my settings. 
Serial can`t print anything.
I don`t know what`s wrong.

**Comment by biomurph** [comment]
Sounds like more of an issue with esp... what sketch are you trying to run? Do you have the right baud rate setting on the serial monitor?

**Comment by YoYoHC** [comment]
run the  PulseSensor_BPM   code and i make the right serial monitor  used 115200,but cant print any data.

**Comment by biomurph** [comment]
OK, That might be your problem.
Please try to use the PulseSensor_BPM_Alternative code. 
The regular BPM code uses hardware interrupts, and that is likely what the problem is. We are not set up to run hardware interrupts on the ESP modules. The BPM_Alternative uses software timing to get the samples, and it works great.
Let us know how it goes.

**Comment by YoYoHC** [comment]
It works.  Thanks!
