### ISSUE TITLE
Is PulseSensor faking heartbeat??

### ISSUE THREAD

**Issue by mabuware** [WorldFamousElectronics/PulseSensorPlayground#94]
So I got the following PulseSensor

![Photo 14 05 19, 08 54 01](https://user-images.githubusercontent.com/7668999/57677964-65312600-7628-11e9-8f4f-9c9c2c6f512f.jpg)
![Photo 14 05 19, 08 53 51](https://user-images.githubusercontent.com/7668999/57677967-65312600-7628-11e9-91f8-d6b460f73ee4.jpg)

and thought I got it to kinda work - but even though the pulse blinking seemed to be somewhat close to the pulse I felt, the blinks didn't seem to really correspond to the beats I felt by hand - so I changed the PulseSensor.cpp code to directly output the measured sensor value, as in

analogWrite(LED_PIN, analogRead(SENSOR_PIN));

and what you see on the video is the led behaviour I get WITHOUT touching the sensor (or even the cable) in any way.

![ezgif-1-e64392a5bf71](https://user-images.githubusercontent.com/7668999/57681415-f061ea00-762f-11e9-90b4-bdbd6a3ae4b2.gif)

Did I get a fake sensor? (it looks like it's got exactly the components it's supposed to have) - or is this the filter and amplifier "feature" of the new hardware version you guys write about on your blog?

I'm a bit bummed and wonder what's going on here

**Comment by biomurph** [comment]
@MrMabulous 
Unfortunately, you got a clone of the legit Pulse Sensor.
Yes, it is made from our design files, but it's impossible to know what exactly is on that thing, so I am not able to trouble-shoot the problem you are having. Since you are getting some weird pulsing of the signal without even having your finger on it, it seems like their circuit is introducing some kind of harmonic oscillation. 

Please support the original makers of Pulse Sensor by purchasing legit hardware.
www.pulsesensor.com
www.amazon.com
www.adafruit.com
www.sparkfun.com
www.mouser.com
www.digikey.com
